[package]
name = "arkecosystem-client"
version = "0.0.1"
authors = ["Juan A. Martín <dev@jaml.pro>"]
description = "A simple Rust API client for the Ark blockchain"
license = "MIT"

[lib]
name = "arkecosystem_client"
path = "src/lib.rs"

[dependencies]
reqwest = "0.8.6"
failure = "0.1.2"
serde_json = "1.0.26"

[dev-dependencies]
mockito = "0.12.0"
