[package]
name = "arkecosystem-client"
version = "0.1.0"
authors = ["Joshua Noack <joshua@ark.io>"]
description = "A simple Rust API client for the ARK Blockchain."
license = "MIT"

[lib]
name = "arkecosystem_client"
path = "src/lib.rs"

[dependencies]
failure = "0.1.3"
reqwest = "0.9.3"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"

[dev-dependencies]
mockito = "0.13.0"
