[package]
name = "arkecosystem-client"
version = "0.1.0"
authors = ["Joshua Noack"]
description = "A simple Rust API client for the ARK Blockchain."
license = "MIT"

[lib]
name = "arkecosystem_client"
path = "src/lib.rs"

[dependencies]
reqwest = "0.8.6"
failure = "0.1.2"
serde = "1.0.75"
serde_derive = "1.0.75"
serde_json = "1.0.26"

[dev-dependencies]
mockito = "0.12.0"
