name: Lint

on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened]

jobs:
    nightly:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Update
              run: rustup update
            - name: Cargo build
              run: |
                  rustup update
                  rustup install nightly
                  rustup run nightly rustc --version --verbose
                  rustup run nightly cargo --version --verbose
                  # Currently only nightly supports this tool
                  RUSTFLAGS="--cfg procmacro2_semver_exempt" rustup run nightly cargo install cargo-tarpaulin
                  rustup run nightly cargo tarpaulin --out Xml
            - name: Clippy
              run: |
                  rustup component add --toolchain nightly clippy
                  rustup run nightly cargo clippy --all-targets --all-features -- -D warnings
            - name: rustfmt
              run: |
                  rustup component add --toolchain nightly rustfmt
                  rustup run nightly cargo fmt -- --check
            - name: Codecov
              run: bash <(curl -s https://codecov.io/bash)

    beta:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Cargo build
              run: |
                  rustup update
                  rustup install beta
                  rustup run beta cargo build
            - name: Clippy
              run: |
                  rustup component add --toolchain beta clippy
                  rustup run beta cargo clippy --all-targets --all-features -- -D warnings
            - name: rustfmt
              run: |
                  rustup component add --toolchain beta rustfmt
                  rustup run beta cargo fmt -- --check

    stable:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Cargo build
              run: |
                  cargo clean
                  cargo build
            - name: Clippy
              run: |
                  rustup update
                  rustup install stable
                  # Clippy is no longer available via crates.io
                  rustup component add --toolchain stable clippy
                  rustup run stable cargo clippy --all-targets --all-features -- -D warnings
            - name: rustfmt
              run: |
                  rustup component add --toolchain stable rustfmt
                  rustup run stable cargo fmt -- --check
