name: Lint

on:
    push:
        branches:
            - "*"
            - "*/*"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    beta:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Cargo build
              run: |
                  rustup update
                  rustup install beta
                  rustup run beta cargo build
            - name: Clippy
              run: |
                  rustup component add --toolchain beta clippy
                  rustup run beta cargo clippy --all-targets --all-features -- -D warnings
            - name: rustfmt
              run: |
                  rustup component add --toolchain beta rustfmt
                  rustup run beta cargo fmt -- --check

    stable:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Cargo build
              run: |
                  cargo clean
                  cargo build
            - name: Clippy
              run: |
                  rustup update
                  rustup install stable
                  # Clippy is no longer available via crates.io
                  rustup component add --toolchain stable clippy
                  rustup run stable cargo clippy --all-targets --all-features -- -D warnings
            - name: rustfmt
              run: |
                  rustup component add --toolchain stable rustfmt
                  rustup run stable cargo fmt -- --check
