name: Test

on:
    push:
        branches:
            - "*"
            - "*/*"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    beta:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Cargo build and test
              run: |
                  rustup update
                  rustup install beta
                  rustup run beta cargo build
                  rustup run beta cargo test
            - name: Codecov
              run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

    stable:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Cargo build and test
              run: |
                  cargo clean
                  cargo build
                  cargo test
            - name: Codecov
              run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
